name: Formatting

on:
    pull_request:
        branches: [main, dev]
        paths:
            - ".github/workflows/format.yml"
            - "src/**"
            - "include/**"
            - "tests/**"
            - ".clang-format"
            - ".clang-tidy"
            - "CMakeLists.txt"

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    fmt:
        permissions:
            contents: read
        runs-on: macos-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Install dependencies
              run: |
                  brew update
                  brew install llvm
                  echo "/opt/homebrew/opt/llvm/bin" >> $GITHUB_PATH
              env:
                  HOMEBREW_NO_AUTO_UPDATE: 1
                  
            - name: Cache build directory
              uses: actions/cache@v4
              with:
                  path: build
                  key: >
                      fmt-${{ runner.os }}-
                      ${{ hashFiles('CMakeLists.txt', 'src/**', 'include/**', 'tests/**') }}
                  restore-keys: |
                      fmt-${{ runner.os }}-

            - name: Configure CMake
              run: cmake -G Ninja -B build

            - name: Check formatting
              run: cmake --build build --target fmt-check

            - name: Static analysis
              run: cmake --build build --target tidy
